### PR TITLE
Ipopt3.0

### PR DESCRIPTION
**Pull request by fdarricau**

### CODE REVIEW

**Comment by bchretien** [comment]
Can you regroup these commits and run a rebase with `3.0` to allow merging? I don't know if the fact that this can't be automatically merged is the reason, but Travis refuses to run for the last commits.

```sh
$ git checkout ipopt3.0
$ git rebase upstream/3.0
$ git rebase -i HEAD~6
```
Then fixup commits and reword the first one (modify the buffer so that it looks like this):
```txt
reword be1773f Eigen::Ref fixes for use with ipopt plugin.
fixup  ec9dbd9 Eigen_ref use: result_ref passing for segments and blocks.
fixup  645cae2 Uninitialized cost_ fix.
fixup  579e001 Some temporaries and copies can be removed.
fixup  80e179c [shared-tests] Synchronize.
fixup  876d4e4 Local constraints_ no more needed.
```

**Comment by fdarricau** [comment]
It is done. Let's see if Travis still refuses to run it.

**Comment by bchretien** [comment]
Travis runs once the automatic merge has been done, and apparently there was some conflicts (rebase seemed to work smoothly locally though...).

**Comment by bchretien** [comment]
LGTM :+1:

**Pull request merged**
